name: flights_mac
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.6.0
  - anyio=4.2.0
  - astroid=2.14.2
  - black=23.11.0
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.12.12
  - cartopy=0.22.0
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.2.0
  - cycler=0.11.0
  - dill=0.3.7
  - distro=1.8.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - geos=3.8.0
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.26.0
  - idna=3.4
  - intel-openmp=2023.1.0
  - isort=5.9.3
  - jpeg=9e
  - jsonpatch=1.33
  - jsonpointer=2.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - langchain-core=0.1.32
  - langchain-openai=0.0.8
  - langsmith=0.1.26
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.5.0
  - libcxx=16.0.6
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libssh2=1.10.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - mccabe=0.7.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openai=1.14.0
  - openjpeg=2.4.0
  - openssl=3.0.13
  - orjson=3.9.15
  - packaging=23.2
  - pandas=2.2.1
  - pathspec=0.10.3
  - pillow=10.2.0
  - pip=23.3.1
  - platformdirs=3.10.0
  - proj=9.3.1
  - pylint=2.16.2
  - pyparsing=3.0.9
  - pyproj=3.6.1
  - pyshp=2.3.1
  - python=3.11.8
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - readline=8.2
  - regex=2023.10.3
  - requests=2.31.0
  - setuptools=68.2.2
  - shapely=2.0.1
  - six=1.16.0
  - sniffio=1.3.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tenacity=8.2.2
  - tiktoken=0.6.0
  - tk=8.6.12
  - tomlkit=0.11.1
  - tornado=6.3.3
  - tqdm=4.65.0
  - typing_extensions=4.9.0
  - tzdata=2024a
  - urllib3=2.1.0
  - wheel=0.41.2
  - wrapt=1.14.1
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - pydantic==2.0.3
      - pydantic-core==2.3.0
      - typing-extensions==4.10.0
