name: flights_win
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.16
  - anyio=4.3.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - astroid=3.1.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - black=24.2.0
  - bleach=6.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.0
  - cycler=0.12.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - docutils=0.20.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fonttools=4.49.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.80.0
  - glib-tools=2.80.0
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.4
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.6
  - imagesize=1.4.1
  - importlib-metadata=7.0.2
  - importlib_metadata=7.0.2
  - importlib_resources=6.3.0
  - iniconfig=2.0.0
  - intel-openmp=2024.0.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - isoduration=20.11.0
  - isort=5.13.2
  - jedi=0.19.1
  - jinja2=3.1.3
  - json5=0.9.22
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter-lsp=2.2.4
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - jupyter_events=0.9.1
  - jupyter_server=2.13.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.1.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.4
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libdeflate=1.19
  - libexpat=2.6.2
  - libffi=3.4.2
  - libglib=2.80.0
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libogg=1.3.4
  - libpng=1.6.43
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libtiff=4.6.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.5
  - libzlib=1.2.13
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - make=4.3
  - markupsafe=2.1.5
  - matplotlib=3.8.3
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mistune=3.0.2
  - mkl=2024.0.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - nbclient=0.10.0
  - nbconvert-core=7.16.2
  - nbformat=5.10.3
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.2.1
  - overrides=7.7.0
  - pandas=2.2.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.12.1
  - patsy=0.5.6
  - pcre2=10.43
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - pluggy=1.4.0
  - ply=3.11
  - prometheus_client=0.20.0
  - psutil=5.9.8
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.17.2
  - pylint=3.1.0
  - pyparsing=3.1.2
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - pytest=8.1.1
  - python=3.11.8
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytz=2024.1
  - pywin32=306
  - pywinpty=2.0.13
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.8
  - referencing=0.33.0
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.18.0
  - scipy=1.12.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.2
  - setuptools=69.2.0
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.1
  - snowballstemmer=2.2.0
  - soupsieve=2.5
  - sphinx=7.2.6
  - sphinx_rtd_theme=2.0.0
  - sphinxcontrib-applehelp=1.0.8
  - sphinxcontrib-devhelp=1.0.6
  - sphinxcontrib-htmlhelp=2.0.5
  - sphinxcontrib-jquery=4.1
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.7
  - sphinxcontrib-serializinghtml=1.1.10
  - stack_data=0.6.2
  - statsmodels=0.14.1
  - tbb=2021.11.0
  - terminado=0.18.1
  - tinycss2=1.2.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.12.4
  - tornado=6.4
  - traitlets=5.14.2
  - types-python-dateutil=2.9.0.20240315
  - typing-extensions=4.10.0
  - typing_extensions=4.10.0
  - typing_utils=0.1.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - uri-template=1.3.0
  - urllib3=2.2.1
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - wheel=0.42.0
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - cartopy==0.22.0
      - dataclasses-json==0.6.4
      - distro==1.9.0
      - frozenlist==1.4.1
      - greenlet==3.0.3
      - jsonpatch==1.33
      - langchain==0.1.12
      - langchain-community==0.0.28
      - langchain-core==0.1.32
      - langchain-openai==0.0.8
      - langchain-text-splitters==0.0.1
      - langsmith==0.1.27
      - marshmallow==3.21.1
      - multidict==6.0.5
      - openai==1.14.1
      - orjson==3.9.15
      - packaging==23.2
      - prompt-toolkit==3.0.43
      - pydantic==2.0.3
      - pydantic-core==2.3.0
      - pyproj==3.6.1
      - pyshp==2.3.1
      - regex==2023.12.25
      - shapely==2.0.3
      - sqlalchemy==2.0.28
      - stack-data==0.6.3
      - tenacity==8.2.3
      - tiktoken==0.6.0
      - tqdm==4.66.2
      - typing-inspect==0.9.0
      - yarl==1.9.4
